source 'https://github.com/CocoaPods/Specs.git'

platform :tvos, '9.0'
use_frameworks!

target 'Example' do
  pod 'TvOSMoreButton', path: '..'
  pod 'TvOSTextViewer'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    next if target.name != 'TvOSTextViewer'

    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.0'
    end
  end
end
