disabled_rules:
  - function_parameter_count
  - identifier_name
  - line_length
  - statement_position
  - trailing_whitespace

excluded:
  - Carthage
  - Example/Pods

colon:
  apply_to_dictionaries: false
