name: Pulls

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: tests-${{ github.head_ref }}
  cancel-in-progress: true

env:
  DEVELOPER_DIR: /Applications/Xcode_13.0.app

jobs:
  linter:
    name: Linters
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - uses: actions/cache@v2
        with:
          path: |
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
            Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: ${{ runner.os }}-pods-
      - run: bundle exec pod repo update
      - run: bundle exec pod install
      - run: bundle exec swiftlint

  tests-unit:
    name: Unit tests
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - uses: actions/cache@v2
        with:
          path: |
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
            Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: ${{ runner.os }}-pods-
      - run: bundle exec pod repo update
      - run: bundle exec pod install
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_13.0.app && /usr/bin/xcodebuild -version
      - name: Run tests
        run: xcodebuild test -scheme TvOSMoreButton -workspace TvOSMoreButton.xcworkspace -destination 'platform=tvOS Simulator,OS=13.0,name=Apple TV' | xcpretty && exit ${PIPESTATUS[0]}
